-- Constants list

local CONST = {}

CONST.ORB_RED = 1
CONST.ORB_BLUE = 2
CONST.ORB_YELLOW = 3
CONST.ORB_GREEN = 4

CONST.COLOR_WHITE = 0xffffff
CONST.COLOR_RED = 0xff0000
CONST.COLOR_GREEN = 0x00ff00
CONST.COLOR_BLUE = 0x0000ff
CONST.COLOR_YELLOW = 0xffff00
CONST.COLOR_BLACK = 0x000000

CONST.SCENE_DIALOG_BG = 1
CONST.SCENE_DIALOG_CHAR = 2
CONST.SCENE_CHOOSE_CHARS = 3
CONST.SCENE_BATTLE = 4

return CONST