LUAC = "D:/Gideros/Tools/luac.exe"

all: .tmp/main.lua.bin .tmp/grass.lua.bin .tmp/summon\ circle.lua.bin .tmp/monster.lua.bin .tmp/magician.lua.bin .tmp/dirt.lua.bin .tmp/cloud.lua.bin

.tmp/main.lua.bin: main.lua
	$(LUAC) -o ".tmp/main.lua.bin" "main.lua"

.tmp/grass.lua.bin: grass.lua
	$(LUAC) -o ".tmp/grass.lua.bin" "grass.lua"

.tmp/summon\ circle.lua.bin: summon\ circle.lua
	$(LUAC) -o ".tmp/summon circle.lua.bin" "summon circle.lua"

.tmp/monster.lua.bin: monster.lua
	$(LUAC) -o ".tmp/monster.lua.bin" "monster.lua"

.tmp/magician.lua.bin: magician.lua
	$(LUAC) -o ".tmp/magician.lua.bin" "magician.lua"

.tmp/dirt.lua.bin: dirt.lua
	$(LUAC) -o ".tmp/dirt.lua.bin" "dirt.lua"

.tmp/cloud.lua.bin: cloud.lua
	$(LUAC) -o ".tmp/cloud.lua.bin" "cloud.lua"

