LUAC = "C:/Program Files (x86)/Gideros/Tools/luac.exe"

all: .tmp/main.lua.bin .tmp/grass.lua.bin .tmp/summon\ circle.lua.bin .tmp/monster.lua.bin .tmp/dirt.lua.bin .tmp/cloud.lua.bin .tmp/misc.lua.bin .tmp/gtween.lua.bin .tmp/easing.lua.bin .tmp/book.lua.bin .tmp/magician.lua.bin .tmp/bubble.lua.bin .tmp/orb.lua.bin .tmp/puzzle.lua.bin

.tmp/main.lua.bin: main.lua
	$(LUAC) -o ".tmp/main.lua.bin" "main.lua"

.tmp/grass.lua.bin: grass.lua
	$(LUAC) -o ".tmp/grass.lua.bin" "grass.lua"

.tmp/summon\ circle.lua.bin: summon\ circle.lua
	$(LUAC) -o ".tmp/summon circle.lua.bin" "summon circle.lua"

.tmp/monster.lua.bin: monster.lua
	$(LUAC) -o ".tmp/monster.lua.bin" "monster.lua"

.tmp/dirt.lua.bin: dirt.lua
	$(LUAC) -o ".tmp/dirt.lua.bin" "dirt.lua"

.tmp/cloud.lua.bin: cloud.lua
	$(LUAC) -o ".tmp/cloud.lua.bin" "cloud.lua"

.tmp/misc.lua.bin: misc.lua
	$(LUAC) -o ".tmp/misc.lua.bin" "misc.lua"

.tmp/gtween.lua.bin: gtween.lua
	$(LUAC) -o ".tmp/gtween.lua.bin" "gtween.lua"

.tmp/easing.lua.bin: easing.lua
	$(LUAC) -o ".tmp/easing.lua.bin" "easing.lua"

.tmp/book.lua.bin: book.lua
	$(LUAC) -o ".tmp/book.lua.bin" "book.lua"

.tmp/magician.lua.bin: magician.lua
	$(LUAC) -o ".tmp/magician.lua.bin" "magician.lua"

.tmp/bubble.lua.bin: bubble.lua
	$(LUAC) -o ".tmp/bubble.lua.bin" "bubble.lua"

.tmp/orb.lua.bin: orb.lua
	$(LUAC) -o ".tmp/orb.lua.bin" "orb.lua"

.tmp/puzzle.lua.bin: puzzle.lua
	$(LUAC) -o ".tmp/puzzle.lua.bin" "puzzle.lua"

